import os
import sys
import requests

discord_webhook = os.environ.get("DISCORD_WEBHOOK_URL")

if not discord_webhook:
    print("Discord webhook URL not found. Skipping notification.")
    sys.exit(0)

# Get the command passed from GitHub Actions (start, success, uploaded, or error)
command = sys.argv[1] if len(sys.argv) > 1 else "start"

if command == "start":
    requests.post(discord_webhook, json={"content": "⏳ **Workflow Started:** The automated nature video factory is now running!"})
    print("Start notification sent.")

elif command == "success":
    # Because HD videos exceed Discord's 25MB webhook limit, we send a text notification instead
    success_message = (
        "✅ **The video successfully generated!**\n\n"
        "🎥 Both your Horizontal (10m) and Vertical (15s) HD nature videos are ready.\n"
        "📥 **How to download:** Head to your GitHub Actions tab to view!"
    )
    payload = {"content": success_message}
    requests.post(discord_webhook, json=payload)
    print("Successfully sent success notification to Discord!")

elif command == "uploaded":
    upload_msg = (
        "🎉 **YouTube Upload Complete!**\n\n"
        "📺 Both videos titled *'Rest up, enjoy the Nature'* have been pushed to your channel."
    )
    requests.post(discord_webhook, json={"content": upload_msg})
    print("Upload notification sent.")

elif command == "error":
    error_msg = "An unknown error occurred during execution."
    
    # Read the error log generated by GitHub Actions
    if os.path.exists("error.log"):
        with open("error.log", "r") as f:
            error_msg = f.read()[-1800:] # Keep under Discord's 2000 character limit
            
    payload = {"content": f"❌ **Workflow Encountered an Error:**\n```python\n{error_msg}\n```"}
    requests.post(discord_webhook, json=payload)
    print("Error notification sent.")
