import os
import sys
import requests

discord_webhook = os.environ.get("DISCORD_WEBHOOK_URL")

if not discord_webhook:
    print("Discord webhook URL not found. Skipping notification.")
    sys.exit(0)

# Get the command passed from GitHub Actions (start, success, or error)
command = sys.argv[1] if len(sys.argv) > 1 else "start"

if command == "start":
    requests.post(discord_webhook, json={"content": "⏳ **Workflow Started:** The automated nature video factory is now running!"})
    print("Start notification sent.")

elif command == "success":
    files_to_upload = ["horizontal_short.mp4", "vertical_short.mp4"]
    for vid_file in files_to_upload:
        if os.path.exists(vid_file):
            print(f"Sending {vid_file} to Discord...")
            with open(vid_file, "rb") as f:
                payload = {"content": f"✅ The video successfully generated: **{vid_file}**"}
                files = {"file": (vid_file, f, "video/mp4")}
                response = requests.post(discord_webhook, data=payload, files=files)
                
                if response.status_code in [200, 204]:
                    print(f"Successfully sent {vid_file} to Discord!")
                else:
                    print(f"Discord upload failed for {vid_file}. Status: {response.status_code}")

elif command == "error":
    error_msg = "An unknown error occurred during execution."
    
    # Read the error log generated by GitHub Actions
    if os.path.exists("error.log"):
        with open("error.log", "r") as f:
            error_msg = f.read()[-1800:] # Keep under Discord's 2000 character limit
            
    payload = {"content": f"❌ **Workflow Encountered an Error:**\n```python\n{error_msg}\n```"}
    requests.post(discord_webhook, json=payload)
    print("Error notification sent.")
