import os
import sys
import json
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# 1. Authorize YouTube Connection
token_env = os.environ.get("YOUTUBE_TOKEN_JSON")
if not token_env:
    print("CRITICAL ERROR: YOUTUBE_TOKEN_JSON is missing from GitHub Secrets.")
    sys.exit(1)

try:
    token_info = json.loads(token_env)
    creds = Credentials.from_authorized_user_info(token_info)
    youtube = build("youtube", "v3", credentials=creds)
except Exception as e:
    print(f"CRITICAL ERROR: Failed to authorize YouTube. {e}")
    sys.exit(1)

# 2. Read Metadata generated by main.py
metadata_file = "video_metadata.json"
if not os.path.exists(metadata_file):
    print(f"CRITICAL ERROR: Metadata file {metadata_file} not found.")
    sys.exit(1)

with open(metadata_file, "r", encoding="utf-8") as f:
    meta = json.load(f)

game_name = meta.get("game_name", "Game Relaxation")
credits_text = meta.get("credits", "")

# 3. COMBINE ALL TOP 3 GAME TAGS (Genshin + Endfield + NTE) FOR MAXIMUM REACH
ALL_GAME_TAGS = [
    "GenshinImpact", "Genshin", "HoYoverse",
    "ArknightsEndfield", "Endfield", "Arknights",
    "NevernessToEverness", "NTE", "HottaStudio"
]

combined_tags_horiz = ALL_GAME_TAGS + ["lofi", "social media detox", "take a break", "relaxing music", "fan content", "study music"]
combined_tags_vert = ALL_GAME_TAGS + ["shorts", "lofi", "relax", "fan content"]

# 4. Define Upload Function
def upload_video(file_path, title, description, tags, category_id="10"): # Category 10 = Music
    if not os.path.exists(file_path):
        print(f"Error: Could not find {file_path} to upload.")
        return
    
    print(f"Uploading {file_path} to YouTube...")
    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": category_id
        },
        "status": {
            "privacyStatus": "public",
            "containsSyntheticMedia": True # Officially flags content as AI-generated
        }
    }
    
    media = MediaFileUpload(file_path, chunksize=-1, resumable=True)
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
    
    try:
        response = request.execute()
        print(f"SUCCESS! Video uploaded. YouTube ID: {response.get('id')}")
    except Exception as e:
        print(f"Upload failed for {file_path}. Error: {e}")

# Build Descriptions
desc_horiz = (
    f"Take a moment to breathe with {game_name}.\n"
    f"Put the phone down, listen to the lofi beats, and rest.\n\n"
    f"--- CREDITS & DISCLAIMER ---\n"
    f"{credits_text}\n\n"
    f"#GenshinImpact #ArknightsEndfield #NevernessToEverness #lofi #socialmediadetox #relax"
)

desc_vert = (
    f"A quick relaxation break with {game_name}. #shorts\n\n"
    f"--- CREDITS ---\n"
    f"{credits_text}\n\n"
    f"#shorts #lofi #relax #fancontent"
)

# 5. Trigger Uploads with [Fan Content] IN FRONT of the title
print(f"--- STARTING YOUTUBE UPLOADS FOR: {game_name} ---")

# Horizontal Upload (10 Minutes)
upload_video(
    file_path="horizontal_short.mp4",
    title=f"[Fan Content] {game_name} - Take a moment to breathe 🌿 Lofi Break",
    description=desc_horiz,
    tags=combined_tags_horiz
)

# Vertical Short Upload (15 Seconds)
upload_video(
    file_path="vertical_short.mp4",
    title=f"[Fan Content] {game_name} - Put the phone down and breathe 🌿 #shorts",
    description=desc_vert,
    tags=combined_tags_vert
)

print("--- YOUTUBE UPLOADS COMPLETE ---")
